package/src/ssr/NextSSRApolloClient.tsx

I just noticed this one when setting up our integration tests.
https://github.com/apollographql/apollo-client/blob/pr/bundling-integrations/integration-tests/next/tests/playwright/apollo-client.test.ts#L10-L14

call `cache.write` independently of `resolve` presence

---

package/README.md

Changing the README to specify that we should use the filename `app/ApolloWrapper.jsx` instead of `app/ApolloWrapper.js` in the _**In SSR**_ section, because there is a React component in there, and we will get `Parsing error: '>' expected eslint` error when it's in `.js` (EDIT: correction it'll only error in Typescript files)
I am using Typescript in this file
- `.js` to `.jsx` in the _**In SSR**_ section

README: Fix js to jsx for SSR

---

.github/workflows/snapshot-release.yml

Just noticed a snapshot release was tagged with `latest` when I just `npm i`'d the library. We don't need every snapshot release to have its own tag (this list would grow infinitely on our npm page while providing basically no utility), so I went with the generic `snapshot` tag that will be shared across all snapshot releases.

fix: tag snapshot npm releases with snapshot tag instead of latest

---

examples/app-dir-experiments/next.config.js
examples/hack-the-supergraph-ssr/next.config.js

I wasn't able to properly test, but on my own separate Next.js instance with the same npm versions works flawflessly without the `appDir: true` flag.
As seen enclosed in the "Good to know" callout:
https://nextjs.org/docs/app/api-reference/next-config-js/appDir

chore: remove experimental flag as it's stable now

---

package/README.md

Apollo 3.8.0 was [released](https://github.com/apollographql/apollo-client/releases/tag/v3.8.0). The rc release warning is no longer needed.

Update README.md to remove Apollo Client rc warning

---

package/package.json
package/src/rsc/registerApolloClient.tsx
yarn.lock

I saw this issue when trying to fetch data from the `sitemap.ts` file using the `getClient` / `registerApolloClient` (like it's done for server only code).
Apparently the "client version" of React is somehow available when the sitemap is getting generated which was triggering the custom detection currently implemented.
I tried using `import 'server-only` instead as it is the recommended way to make sure something isn't imported from a client component and all cases seem to work:
- From CC -> crash (✅ )
- From RSC -> ✅ 
- From sitemap.ts -> ✅

Use server-only package instead of custom environment detection

---

package/src/ssr/NextSSRApolloClient.tsx

Move cleanup out of Observer subscription initializer

---

.github/workflows/tests.yml
package/src/ssr/NextSSRApolloClient.tsx

See changes in https://github.com/apollographql/apollo-client/pull/11345
Unfortunately, we already bumped the dependencies for the alphas/betas/rcs, so we can't just force an update that way.

prepare for change in `QueryManager.inFlightLinkObservable` (Apollo Client 3.9 beta)

---

integration-test/.env.local
integration-test/package.json
integration-test/src/app/cc/ApolloWrapper.tsx
integration-test/src/app/cc/dynamic/dynamic.test.ts
integration-test/src/app/cc/dynamic/layout.tsx
integration-test/src/app/cc/static/layout.tsx
integration-test/src/app/graphql/route.ts
integration-test/src/app/graphql/schema.ts
integration-test/src/app/rsc/client.ts
integration-test/src/middleware.ts
package/src/ssr/ApolloNextAppProvider.tsx
package/src/ssr/RehydrationContext.tsx
yarn.lock

Rehydration currently does not work in an app with a CSP that disables unsafe-inline scripts.
With this change, you can now follow the [NextJS guide](https://nextjs.org/docs/app/building-your-application/configuring/content-security-policy) on CSP, and in `layout.tsx` or `page.tsx` pass the `nonce` from headers down into the `ApolloWrapper` to prevent `unsafe-inline` CSP errors.

feat: add support for passing a nonce to the rehydration script

---

package/.eslintrc.js
package/src/ssr/AccumulateMultipartResponsesLink.test.ts
package/src/ssr/AccumulateMultipartResponsesLink.ts
package/src/ssr/ApolloNextAppProvider.tsx
package/src/ssr/ApolloRehydrateSymbols.tsx
package/src/ssr/NextSSRApolloClient.tsx
package/src/ssr/NextSSRInMemoryCache.tsx
package/src/ssr/RehydrationContext.tsx
package/src/ssr/RemoveMultipartDirectivesLink.test.ts
package/src/ssr/RemoveMultipartDirectivesLink.ts
package/src/ssr/dataTransport.ts
package/src/ssr/types.tsx

This should especially tree-shake a large part of the `graphql` package that showed up in https://github.com/apollographql/apollo-client-nextjs/issues/126#issuecomment-1875590159

reduce bundle size by adjusting imports

---

.github/workflows/tests.yml
package/package.json
package/src/ssr/NextSSRApolloClient.tsx
yarn.lock

This PR drops the workarounds for this package to work with both AC 3.8 and 3.9 and bumps the minimum `peerDependency` version to 3.9.

Drop workarounds to work with both Apollo Client 3.8 and 3.9

---

package/README.md

Removed unnecessary mention of the rc version of the @apollo/client package. This should remove confusion around which version should be installed. See https://github.com/apollographql/apollo-client-nextjs/releases/tag/v.0.8.0

Removing confusing installation language in README.md

---

packages/client-react-streaming/src/DataTransportAbstraction/WrappedApolloClient.test.tsx
packages/client-react-streaming/src/DataTransportAbstraction/WrappedApolloClient.tsx
packages/client-react-streaming/src/importErrors.test.tsx
packages/client-react-streaming/src/util/runInConditions.ts

I believe this would fix #256
While the `__typename` transform normally is applied in both queries happening during SSR, and in the Browser, in the case where a query could not fully be transported from SSR to the Browser (e.g. in the case an error was thrown on the server, or because the stream closed before it was fully transported over), these would be replayed as "simulated queries", and in that case the transform was not applied.
Hint for review: hide whitespace :)

apply documentTransforms before rerunning simulated queries

---

.github/workflows/tests.yml
packages/client-react-streaming/src/AccumulateMultipartResponsesLink.test.ts
packages/client-react-streaming/src/RemoveMultipartDirectivesLink.test.ts

These tests fail from time to time, e.g. in this run: https://github.com/apollographql/apollo-client-nextjs/actions/runs/8523111570/job/23344752684
Let's see if we get them more stable?

try to stabilize flimsy tests

---

packages/client-react-streaming/src/DataTransportAbstraction/WrappedApolloClient.test.tsx
packages/client-react-streaming/src/DataTransportAbstraction/WrappedApolloClient.tsx
packages/client-react-streaming/src/importErrors.test.tsx
packages/client-react-streaming/src/registerApolloClient.test.tsx

closes #238
The last PR for 0.10.0.
This defaults `connectToDevTools` to `false` in RSC and SSR builds where connecting to the DevTools is impossible anyways, but might end up in a stray `setTimeout` that hangs around for 10 seconds which uses memory unneccessarily - and e.g. prevents tests from cleaning up correctly.
No tests for this since I'm not sure how correctly to test this - but I could remove a few `connectToDevTools` from our tests, which is nice. I looked at the built artefacts though, and it's picked up correctly.

0.10.0 (4) default `connectToDevTools` to `false` in RSC and SSR builds

---

.github/renovate.json5
integration-test/yarn.lock
package.json
packages/client-react-streaming/package.json
packages/client-react-streaming/src/ManualDataTransport/ApolloRehydrateSymbols.tsx
packages/client-react-streaming/src/ManualDataTransport/ManualDataTransport.tsx
packages/client-react-streaming/src/ManualDataTransport/RehydrationContext.tsx
packages/client-react-streaming/src/ManualDataTransport/dataTransport.test.ts
packages/client-react-streaming/src/ManualDataTransport/dataTransport.ts
packages/client-react-streaming/src/ManualDataTransport/serialization.test.ts
packages/client-react-streaming/src/ManualDataTransport/serialization.ts
packages/client-react-streaming/tsup.config.ts
yarn.lock

closes #209
This is a big bundle size reduction for the library itself (see below, -44.93% on what we ship to the browser with the Next.js package), but beyond that it also cuts down a lot on data transported by the library, as SuperJSON adds a lot of extra bulk in their serialization format that we just don't need.
That said, some of our users might have non-serializable values in the cache and also want that transported over, so I'm leaving an escape hatch: `stringify` and `revive` can be configured.

remove superjson dependency

---

integration-test/yarn.lock
packages/client-react-streaming/src/DataTransportAbstraction/DataTransportAbstraction.ts
packages/client-react-streaming/src/DataTransportAbstraction/WrappedApolloClient.test.tsx
packages/client-react-streaming/src/DataTransportAbstraction/WrappedApolloClient.tsx
packages/client-react-streaming/src/DataTransportAbstraction/printMinified.tsx

Right now, we transport the AST of a query over the network.
That's not optimal:
Normal Query:
```gql
query dynamicProducts {
products {
id
title
foo {
bar {
baz {
yoink
}
}
}
}
}
```
is instead transported as
```json
{
"kind": "Document",
"definitions": [
{
"kind": "OperationDefinition",
"operation": "query",
"name": {
"kind": "Name",
"value": "dynamicProducts"
},
"variableDefinitions": [],
"directives": [],
"selectionSet": {
"kind": "SelectionSet",
"selections": [
{
"kind": "Field",
"name": {
"kind": "Name",
"value": "products"
},
"arguments": [],
"directives": [],
"selectionSet": {
"kind": "SelectionSet",
"selections": [
{
"kind": "Field",
"name": {
"kind": "Name",
"value": "id"
},
"arguments": [],
"directives": []
},
{
"kind": "Field",
"name": {
"kind": "Name",
"value": "title"
}, …
```

Transport minified version of query.

---

integration-test/yarn.lock
packages/experimental-nextjs-app-support/src/ApolloNextAppProvider.ts

Allow using the browser build of `ApolloNextAppProvider` outside of Next.js, e.g. for tests.

---

packages/experimental-nextjs-app-support/README.md

Hi, I noticed that the links to `useSuspenseQuery` and `useFragment` weren't linking to the proper place. It looks like those hooks got moved out of experimental and are stable now. I updated those links. Looks like my editor also cleared out some trailing whitespace, hopefully that is okay.

Update README links to point to non-experimental hooks links

---

packages/experimental-nextjs-app-support/README.md

https://github.com/apollographql/apollo-client-nextjs/pull/309/files#r1628079676
As noted in the other PR, GFM actually supports double spaces as line breaks (https://github.github.com/gfm/#hard-line-breaks), who knew! 
This uses the other option of `\` to indicate a line break so editors don't automatically clean it up and cause issues in the future

Use \ instead of double spaces to add line breaks

---

integration-test/yarn.lock
packages/client-react-streaming/src/transportedQueryRef.ts

(temporarily?) remove `queryRef.toPromise()`

---

integration-test/nextjs/package.json
integration-test/yarn.lock

This was reported as problematic in #336, let's see.

integration-test: bump `next` to 14.1.1

---

packages/client-react-streaming/src/ManualDataTransport/ApolloRehydrateSymbols.tsx
packages/client-react-streaming/src/ManualDataTransport/ManualDataTransport.tsx
packages/client-react-streaming/src/ManualDataTransport/index.ts

This should fix the issue with an hydration error of `useQuery` that came up in #368, where no suspense boundary existed and as a result, the `useRef` of `ManualDataTransport` became re-initialized.

make the hook hydration cache resilient against unmounted recreation of `ManualDataTransport`

---

integration-test/nextjs/src/app/rsc/client.ts
integration-test/nextjs/src/app/rsc/dynamic/PreloadQuery/queryRef-refTest/RefTestChild.tsx
integration-test/yarn.lock
packages/client-react-streaming/src/DataTransportAbstraction/WrappedApolloClient.tsx

I've seen this a few times too often now.

Warn if `ssrMode` or `ssrForceFetchDelay` are used.

---

integration-test/yarn.lock
packages/client-react-streaming/tsup.config.ts

I'm not sure when and why that happened, but it seems like we've been bundling parts of the `graphql` package in recent releases.
This fixes that.

do not bundle parts of the `graphql` package

---

.github/workflows/vercel-integration.yml

We have two deployments now and I also renamed it - so this ensures that the e2e tests for Next.js only run for Next.js deployments

run playwright tests only against next.js deployment

---

packages/tanstack-start/package.json
yarn.lock

```
p41e2b → ✘ @apollo/client-integration-tanstack-start@npm:0.12.0-alpha.0 [400a2] doesn't provide graphql to @apollo/client-react-streaming@npm:0.12.0-alpha.0 [98aaf]
pcc06b → ✘ @apollo/client-integration-tanstack-start@npm:0.12.0-alpha.0 [400a2] doesn't provide react-dom to @apollo/client-react-streaming@npm:0.12.0-alpha.0 [98aaf]
```
Whoops sorry about duplicating the PR was deleting all the branches on my new fork and accidentally hit this branch too.

Fix peer deps for tanstack lib

---

.changeset/strange-boats-type.md
packages/client-react-streaming/src/stream-utils/createInjectionTransformStream.test.tsx
packages/client-react-streaming/src/stream-utils/createInjectionTransformStream.tsx

Fixes an issue where `createInjectionTransformStream` fails to inject any cache data into SSR output when the closing `</head>` happened to fall across the boundary between 2 chunks.
Fixes #431

Handle closing head tag split across chunks

---

.changeset/heavy-seals-notice.md
packages/client-react-streaming/src/DataTransportAbstraction/WrappedApolloClient.tsx

This pairs with https://github.com/apollographql/apollo-client/pull/12566

Call `removeQuery` instead of `stopQuery`

---

.changeset/calm-snakes-mate.md
packages/tanstack-start/src/routerWithApolloClient.tsx

With the typing of `context.preloadQuery` in the tanstack start intergration, It's possible to write code like this in a loader:
```ts
const _movieQueryRef = preloadQuery(GET_MOVIES_SEARCH, {
variables: {
search: query,
page,
},
});
const movieQueryRef = await _movieQueryRef.toPromise();
return { movieQueryRef };
```
(This is similar to how `ensureQueryData` would be used in an Tanstack Start and Query application)
However, because in start loaders are isomorphic, in server mode the `moveQueryRef` is typed as a `PreloadedQueryRef` when it's actually a `PreloadedQueryRef` on the browser and a `TransportedQueryRef` on the server. `toPromise` does not exist right now on `TransportedQueryRef` so you get a null error that was not caught by the Blessed Squiggly Line in Code/Cursor/Typescript …

change preloadQuery tanstack to transport query preload function
